apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 80  # Port you want to expose on the Service
      targetPort: 8080  # Port your Spring Boot app is listening on in the Pods
  type: LoadBalancer  # Expose the Service outside the cluster
