apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80  # Port you want to expose on the Service
      targetPort: 80  # Port your React app is listening on in the Pods
  type: LoadBalancer  # Expose the Service outside the cluster
